version: "3.8"

services:
  api1:
    build: .
    env_file:
      - .env
    ports:
      - "3001:3000"

  api2:
    build: .
    env_file:
      - .env
    ports:
      - "3002:3000"

  api3:
    build: .
    env_file:
      - .env
    ports:
      - "3003:3000"

  api4:
    build: .
    env_file:
      - .env
    ports:
      - "3004:3000"

  nginx:
    image: nginx:1.25
    container_name: nginx_lb
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
      - api3
      - api4
