version: "3.8"

services:
  api:
    build: .
    env_file:
      - .env
    expose:
      - "3000"
  nginx:
    image: nginx:1.25
    container_name: nginx_lb
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
