version: "3.8"

services:
  api:
    build: .
    env_file:
      - .env.docker
    expose:
      - "5000"
  nginx:
    image: nginx:1.25
    container_name: nginx_lb
    ports:
      - "${INGEST_PORT}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
